# Form implementation generated from reading ui file 'nhl_home.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMainWindow, QApplication
import home_window_UI
from database import db_upcoming_matches

class Ui_MainWindow(QMainWindow):

    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        self.setupUi()

    def setupUi(self):



        self.resize(926, 671)
        self.centralwidget = QtWidgets.QWidget(parent=self)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setObjectName("nhl_home_label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)

        # create main container for bets area
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 500))
        self.groupBox_2.setObjectName("main_groupBox")

        # set layout as vertical for all objects in main container
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("layout_for_bet_boxes")

        """
        tuple documentation for upcoming_matches:

        id - string
        home - string
        home_odds - int
        away - string
        away_odds - int
        date - string ('month, day') ex. Apr 12
        time - string in military time
        """

        # # connect to database
        # db = db_upcoming_matches.ConnectDbUpcomingMatch()
        #
        # self.groupbox_increment = 0
        # self.pushbutton_increment = 0
        #
        #
        #
        # # logic to make buttons
        # for match in db.get_all_matches():
        #
        #
        #
        #
        #
        #
        #         self.groupbox_increment += 1
        #         self.pushbutton_increment += 1
        #



        self.groupBox_5 = QtWidgets.QGroupBox(parent=self.groupBox_2)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 20))
        self.groupBox_5.setObjectName("model")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_5)
        self.label_4.setMinimumSize(QtCore.QSize(0, 20))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.groupBox_5)
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_3.addWidget(self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.groupBox_5)
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_3.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(parent=self.groupBox_5)
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_3.addWidget(self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton(parent=self.groupBox_5)
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout_3.addWidget(self.pushButton_15)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(parent=self.groupBox_2)
        self.groupBox_6.setMinimumSize(QtCore.QSize(0, 20))
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_5.setMinimumSize(QtCore.QSize(0, 20))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.pushButton_16 = QtWidgets.QPushButton(parent=self.groupBox_6)
        self.pushButton_16.setObjectName("pushButton_16")
        self.verticalLayout_4.addWidget(self.pushButton_16)
        self.pushButton_17 = QtWidgets.QPushButton(parent=self.groupBox_6)
        self.pushButton_17.setObjectName("pushButton_17")
        self.verticalLayout_4.addWidget(self.pushButton_17)
        self.pushButton_18 = QtWidgets.QPushButton(parent=self.groupBox_6)
        self.pushButton_18.setObjectName("pushButton_18")
        self.verticalLayout_4.addWidget(self.pushButton_18)
        self.pushButton_19 = QtWidgets.QPushButton(parent=self.groupBox_6)
        self.pushButton_19.setObjectName("pushButton_19")
        self.verticalLayout_4.addWidget(self.pushButton_19)
        self.verticalLayout_2.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(parent=self.groupBox_2)
        self.groupBox_7.setMinimumSize(QtCore.QSize(0, 20))
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox_7)
        self.label_6.setMinimumSize(QtCore.QSize(0, 20))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.pushButton_20 = QtWidgets.QPushButton(parent=self.groupBox_7)
        self.pushButton_20.setObjectName("pushButton_20")
        self.verticalLayout_5.addWidget(self.pushButton_20)
        self.pushButton_21 = QtWidgets.QPushButton(parent=self.groupBox_7)
        self.pushButton_21.setObjectName("pushButton_21")
        self.verticalLayout_5.addWidget(self.pushButton_21)
        self.pushButton_22 = QtWidgets.QPushButton(parent=self.groupBox_7)
        self.pushButton_22.setObjectName("pushButton_22")
        self.verticalLayout_5.addWidget(self.pushButton_22)
        self.pushButton_23 = QtWidgets.QPushButton(parent=self.groupBox_7)
        self.pushButton_23.setObjectName("pushButton_23")
        self.verticalLayout_5.addWidget(self.pushButton_23)
        self.verticalLayout_2.addWidget(self.groupBox_7)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.verticalLayout.addWidget(self.groupBox, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:700;\">NHL Home</span></p></body></html>"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.groupBox_5.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_4.setText(_translate("MainWindow", "Team A vs Team B"))
        self.pushButton_12.setText(_translate("MainWindow", "moneyline Team A"))
        self.pushButton_13.setText(_translate("MainWindow", "moneyline Team B"))
        self.pushButton_14.setText(_translate("MainWindow", "Over"))
        self.pushButton_15.setText(_translate("MainWindow", "Under"))
        self.groupBox_6.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_5.setText(_translate("MainWindow", "Team A vs Team B"))
        self.pushButton_16.setText(_translate("MainWindow", "moneyline Team A"))
        self.pushButton_17.setText(_translate("MainWindow", "moneyline Team B"))
        self.pushButton_18.setText(_translate("MainWindow", "Over"))
        self.pushButton_19.setText(_translate("MainWindow", "Under"))
        self.groupBox_7.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_6.setText(_translate("MainWindow", "Team A vs Team B"))
        self.pushButton_20.setText(_translate("MainWindow", "moneyline Team A"))
        self.pushButton_21.setText(_translate("MainWindow", "moneyline Team B"))
        self.pushButton_22.setText(_translate("MainWindow", "Over"))
        self.pushButton_23.setText(_translate("MainWindow", "Under"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.pushButton.setText(_translate("MainWindow", "{balance}"))
        self.pushButton_2.setText(_translate("MainWindow", "Home"))
        self.pushButton_3.setText(_translate("MainWindow", "My Bets"))

        self.pushButton_2.clicked.connect(self.home_button_clicked)




    def home_button_clicked(self):
        self.home_window = home_window_UI.Ui_MainWindow()
        self.home_window.show()
        self.close()


if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    window = Ui_MainWindow()
    window.show()
    sys.exit(app.exec())

